# Generated by Django 3.2.12 on 2023-10-06 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 10, 6, 6, 25, 22, 347014, tzinfo=utc), verbose_name='Date OF Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2023, 10, 6, 6, 25, 35, 875079, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
